[package]
name = "sieve-cache"
version = "0.1.0"
edition = "2021"
description = "SIEVE cache replacement policy"
homepage = "https://github.com/jedisct1/rust-sieve-cache"
keywords = ["cache"]
license = "MIT"
authors = ["Frank Denis <github@pureftpd.org>"]
categories = ["algorithms", "caching"]

[dependencies]
